---
- hosts: "{{ targets }}"
  connection: local
  gather_facts: False

  tasks:
  - name: create discovery group
    uri: 
      url: https://192.168.1.142/api/DiscoveryConfigService/DiscoveryConfigGroups
      user: admin
      password: P@ssw0rd
      method: POST
      headers:
        content-type: application/json  
      body: {"DiscoveryConfigGroupName":"Discovery Devices","DiscoveryConfigGroupDescription":"null","DiscoveryConfigModels":[{"DiscoveryConfigId":1,"DiscoveryConfigDescription":"","DiscoveryConfigStatus":"","DiscoveryConfigTargets":[{"DiscoveryConfigTargetId":0,"NetworkAddressDetail":"192.168.1.128","AddressType":30,"Disabled":false,"Exclude":false}],"ConnectionProfileId":0,"ConnectionProfile":"{\"profileName\":\"\",\"profileDescription\":\"\",\"type\":\"DISCOVERY\",\"credentials\":[{\"id\":0,\"type\":\"WSMAN\",\"authType\":\"Basic\",\"modified\":false,\"credentials\":{\"username\":\"root\",\"password\":\"calvin\",\"caCheck\":false,\"cnCheck\":false,\"port\":443,\"retries\":3,\"timeout\":60,\"isHttp\":false,\"keepAlive\":false}}]}","DeviceType":[1000]}],"Schedule":{"RunNow":true,"RunLater":false,"Cron":"startnow","StartTime":"","EndTime":""},"CreateGroup":true,"TrapDestination":false}  
      body_format: json
      validate_certs: no
      status_code: 201
      return_content: yes
...
