---
- name: server template assignment
  hosts: "{{ targets }}"
  connection: local
  gather_facts: False
  vars:
    ome_user: admin
    ome_password: P@ssw0rd

  collections:
    - dellemc.openmanage
    - ansible.builtin

  tasks:
    - name: assign template to server
      ome_template:
        hostname: "{{ inventory_hostname }}"
        username: "{{ ome_user }}"
        password: "{{ ome_password }}"
        validate_certs: false
        command: "deploy"
        template_id: "{{ id }}"
        device_service_tag:
          - "{{ svc_tag }}"
      tags:
        - deploy_template

# example)  ansible-playbook ome_assign_template.yml -i inventory.yml -e "targets=ome svc_tag=6FTN9Z1 id=20"
# /home/rob/playbooks/Mycode/ansible/dev/102722
...
