---
- name: server profile delete
  hosts: "{{ targets }}"
  connection: local
  gather_facts: False
  vars:
    ome_user: admin
    ome_password: P@ssw0rd

  collections:
    - dellemc.openmanage
    - ansible.builtin

  tasks:
    - name: delete profile
      ome_profile:
        hostname:   "{{ inventory_hostname }}"
        username: "{{ ome_user }}"
        password:  "{{ ome_password }}"
        validate_certs: false
        command: delete
        filters:
          SelectAll: True
          Filters: =contains(ProfileName,'{{ svc_tag }}')
      ignore_errors: True

# example) ansible-playbook ome_assign_profile.yml -i inventory.yml -e "targets=ome svc_tag=6FTN9Z1"
# /home/rob/playbooks/Mycode/ansible/dev/102722
...
